version: '3'
services:
  service1:
    image: service1-image
    build:
      context: ./service1
    ports:
      - "8080:8080"

  service2:
    image: service2-image
    build:
      context: ./service2
    ports:
      - "8081:8080"
