spring:
  application:
    name: myproject
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:8888"
management:
  endpoints:
    web:
      exposure:
        include: refresh,health, circuitbreakers, metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: "API Services - Documentación"
    version: "1.0.0"
    description: "Documentación de las APIs reactivas del proyecto"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
