openapi: 3.0.1
info:
  title: Customer Service API
  version: 1.0.0
paths:
  /customers:
    post:
      summary: Crear cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
      responses:
        '201':
          description: Cliente creado
  /customers/{id}:
    get:
      summary: Obtener cliente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cliente encontrado
components:
  schemas:
    CustomerRequest:
      type: object
      properties:
        name:
          type: string
        document:
          type: string
